### ISSUE TITLE
[Bug] Incompatibility between absorbtion hearts and gapple / notch apple

### ISSUE THREAD

**Issue by anhgelus** [msmp-mc/altered-respawn#7]
When we eat a golden apple (or a notch apple) after beeing revived, our hearts will do this:

1. First time, regive you all your absorbtion hearts
2. Other times, never give your absorbtion hearts

**Comment by Akik4** [comment]
2 way to solve this
- We custom Gapple State
- We didn't give Absorbtion

**Comment by anhgelus** [comment]
I think we can remove the absorption and replace it by a resistance effect or smtg like that

**Comment by Akik4** [comment]
Removed for the moment
Follow AddingTiers next Commit
