### ISSUE TITLE
[Feat] Disable "high flying" for spectator

### ISSUE THREAD

**Issue by anhgelus** [msmp-mc/altered-respawn#9]
When a spectator decide to go to a high flying (higher than the walls), he can try to find the exit.

To fix it, we must rollback the user after beeing at this state.

**Comment by Akik4** [comment]
More simple he can choose a player in specator mode and we can define a zone who he can fly like 10*10*10

**Comment by anhgelus** [comment]
Yeah, nice idea

**Comment by Akik4** [comment]
Fixed
